using System.Text.RegularExpressions;
using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using System.Threading;
using System;
using TestProject.SDK;
using TestProject.SDK.Tests.Helpers;
using TestProject.SDK.Tests;
using TestProject.Common.Attributes;
using TestProject.Common.Enums;

namespace TestProject.Generated.Tests.Temperaturas
{
	/// <summary>
	/// This class was automatically generated by TestProject
	/// Project: Temperaturas
	/// Test: Test_Temp_Incorrectas
	/// Generated by: ANDRES BARRERA (sebacant7@hotmail.com)
	/// Generated on: 10/12/2021 02:05:21
	/// </summary>
	public class TestTempIncorrectas : IWebTest
	{
		[ParameterAttribute(Description = "Auto generated application URL parameter", DefaultValue = "http://localhost:3000/", Direction = ParameterDirection.Input)]
		public string ApplicationURL;
		[ParameterAttribute(Direction = ParameterDirection.Input)]
		public string Ciudad;
		public ExecutionResult Execute(WebTestHelper helper)
		{
			var driver = helper.Driver;
			var report = helper.Reporter;
			bool boolResult;
			By by;
			
			// set timeout for driver actions (similar to step timeout)
			driver.Timeout = 15000;
			
			 // 1. Navigate to '{{ApplicationURL}}'
			// Navigates the specified URL (Auto-generated)
			// Add step sleep time (Before)
			Thread.Sleep(500);
			boolResult = driver.TestProject().NavigateToURL(ApplicationURL);
			report.Step(string.Format("Navigate to '{0}'", ApplicationURL), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 2. Click 'Ver Temperaturas'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.XPath("//a[. = 'Ver Temperaturas']");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'Ver Temperaturas'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 3. Click 'Buscar...'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.XPath("//input[@placeholder = 'Buscar...']");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'Buscar...'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 4. Type '{{Ciudad}}' in 'Buscar...'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.XPath("//input[@placeholder = 'Buscar...']");
			boolResult = driver.TestProject().TypeText(by, Ciudad);
			report.Step(string.Format("Type '{0}' in 'Buscar...'", Ciudad), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 5. Send 'ENTER' key(s)
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.XPath("//input[@placeholder = 'Buscar...']");
			boolResult = driver.TestProject().SendKeys(by, "ENTER");
			report.Step("Send 'ENTER' key(s)", boolResult, TakeScreenshotConditionType.Failure);
			
			return ExecutionResult.Passed;
		}
	}
}