using System.Text.RegularExpressions;
using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using System.Threading;
using System;
using TestProject.SDK;
using TestProject.SDK.Tests.Helpers;
using TestProject.SDK.Tests;
using TestProject.Common.Attributes;
using TestProject.Common.Enums;

namespace TestProject.Generated.Tests.Temperaturas
{
	/// <summary>
	/// This class was automatically generated by TestProject
	/// Project: Temperaturas
	/// Test: Test_Temperatura_Manual
	/// Generated by: ANDRES BARRERA (sebacant7@hotmail.com)
	/// Generated on: 10/12/2021 02:06:03
	/// </summary>
	public class TestTemperaturaManual : IWebTest
	{
		[ParameterAttribute(Description = "Auto generated application URL parameter", DefaultValue = "http://localhost:3000/", Direction = ParameterDirection.Input)]
		public string ApplicationURL;
		[ParameterAttribute(DefaultValue = "Bogota", Direction = ParameterDirection.Input)]
		public string Ciudad;
		[ParameterAttribute(DefaultValue = "15", Direction = ParameterDirection.Input)]
		public string Temperatura;
		[ParameterAttribute(DefaultValue = "27/09/2021", Direction = ParameterDirection.Input)]
		public string Fecha;
		public ExecutionResult Execute(WebTestHelper helper)
		{
			var driver = helper.Driver;
			var report = helper.Reporter;
			bool boolResult;
			By by;
			
			// set timeout for driver actions (similar to step timeout)
			driver.Timeout = 15000;
			
			 // 1. Navigate to '{{ApplicationURL}}'
			// Navigates the specified URL (Auto-generated)
			// Add step sleep time (Before)
			Thread.Sleep(500);
			boolResult = driver.TestProject().NavigateToURL(ApplicationURL);
			report.Step(string.Format("Navigate to '{0}'", ApplicationURL), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 2. Click 'Ingresar Temperatura'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.XPath("//a[. = 'Ingresar Temperatura']");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'Ingresar Temperatura'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 3. Click 'ciudad'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("[name='ciudad']");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'ciudad'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 4. Type '{{Ciudad}}' in 'ciudad'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("[name='ciudad']");
			boolResult = driver.TestProject().TypeText(by, Ciudad);
			report.Step(string.Format("Type '{0}' in 'ciudad'", Ciudad), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 5. Click 'temp'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("[name='temp']");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'temp'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 6. Type '{{Temperatura}}' in 'temp'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("[name='temp']");
			boolResult = driver.TestProject().TypeText(by, Temperatura);
			report.Step(string.Format("Type '{0}' in 'temp'", Temperatura), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 7. Click 'fecha'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("[name='fecha']");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'fecha'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 8. Click 'fecha'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("[name='fecha']");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'fecha'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 9. Type '{{Fecha}}' in 'fecha'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("[name='fecha']");
			boolResult = driver.TestProject().TypeText(by, Fecha);
			report.Step(string.Format("Type '{0}' in 'fecha'", Fecha), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 10. Click 'Guardar'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.XPath("//button[. = 'Guardar']");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'Guardar'", boolResult, TakeScreenshotConditionType.Failure);
			
			return ExecutionResult.Passed;
		}
	}
}